---
# tasks file for mercurial

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: mercurial

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: mercurial

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: mercurial
